### ISSUE TITLE
Incorrect target folder when having many entry points

### ISSUE THREAD

**Issue by enepomnyaschih** [elwin013/parcel-plugin-static-files-copy#43]
When I run:

`node_modules/.bin/parcel src/*/index.html`

I expect my static files to be copied to `dist` folder. Instead, it takes the first available bundle (e.g. `src/a/index.html`) and copies all static files to its subfolder (here: `dist/a`). It doesn't make any sense. How can I deal with this problem?

The reason is obviously in this line:

`const bundleDir = path.dirname(bundle.name || bundler.mainBundle.childBundles.values().next().value.name);`

Node 12.16.1
NPM 6.14.4
Parcel 1.12.4
Plugin 2.3.1
Windows 10

**Comment by enepomnyaschih** [comment]
Dirty workaround:

`node_modules/.bin/parcel src/dummy.html src/*/index.html`

**Comment by elwin013** [comment]
hello @enepomnyaschih,
thank you for reporting this. From v2.3.3 (and v2.3.4) there will be different behavior:
* if `staticOutDir` starts with `/` then static files will be put into out dir specified by parcel,
* otherwise static files will be put in every bundle.

Please see `examples` directory to see how it works (`multiple-entry-points` and `multiple-entry-points-with-common-static`)

Hope that helps. :-)

**Comment by enepomnyaschih** [comment]
Thank you! Unfortunately, I can't check this fix, because we've decided to switch back from Parcel to WebPack because of its [instability](https://github.com/parcel-bundler/parcel/issues/4398). But I believe that Parcel has a great potential, so hopefully we'll be able to try it again in the future.
